"""Code generator: a validated Program -> a standalone importable Python module.

The emitted module reconstructs the program as plain data and exposes ``match``
and ``dispatch`` backed by ``dianalang.runtime`` (the language's small runtime
library — the way compiled C still links libc). The data table is human-readable
so the artifact is auditable.
"""
from __future__ import annotations

from . import nodes


def _lit(v) -> str:
    return repr(v)


def _emit_constraint(c) -> str:
    if c is None:
        return "None"
    if isinstance(c, nodes.Range):
        return f"nodes.Range(lo={_lit(c.lo)}, hi={_lit(c.hi)})"
    if isinstance(c, nodes.Enum):
        return f"nodes.Enum(choices={_lit(c.choices)})"
    if isinstance(c, nodes.MaxLen):
        return f"nodes.MaxLen(n={_lit(c.n)})"
    raise TypeError(f"unknown constraint {c!r}")


def _emit_arg(a: nodes.Arg) -> str:
    return (f"nodes.Arg(name={_lit(a.name)}, type={_lit(a.type)}, "
            f"constraint={_emit_constraint(a.constraint)})")


def _emit_runner(r) -> str:
    if isinstance(r, nodes.ShellRunner):
        return f"nodes.ShellRunner(template={_lit(r.template)})"
    if isinstance(r, nodes.ArgvRunner):
        return f"nodes.ArgvRunner(tokens={_lit(r.tokens)})"
    if isinstance(r, nodes.ReadRunner):
        return f"nodes.ReadRunner(path_template={_lit(r.path_template)})"
    if isinstance(r, nodes.ReplyOnlyRunner):
        return "nodes.ReplyOnlyRunner()"
    return "None"


def _emit_skill(s: nodes.Skill) -> str:
    args = ", ".join(_emit_arg(a) for a in s.args)
    return (
        "    nodes.Skill(\n"
        f"        name={_lit(s.name)},\n"
        f"        utters={_lit(s.utters)},\n"
        f"        args=[{args}],\n"
        f"        danger={_lit(s.danger)},\n"
        f"        runner={_emit_runner(s.runner)},\n"
        f"        reply={_lit(s.reply)},\n"
        "    ),"
    )


_HEADER = '''\
"""Auto-generated by DianaLang from {source}. Do not edit by hand.

Regenerate with:  dianac build {source} -o {out}
"""
from dianalang import nodes
from dianalang.runtime import match as _match, execute as _execute

PROGRAM = nodes.Program(skills=[
{skills}
])


def match(utterance):
    """Return the best Match for an utterance, or None."""
    return _match(PROGRAM, utterance)


def dispatch(utterance, gate=None, dry_run=False):
    """Match + execute. Returns an ExecResult, or None if nothing matched.
    `gate(skill) -> bool` authorizes 'confirm'/'sudo' skills at the choke point."""
    m = _match(PROGRAM, utterance)
    if m is None:
        return None
    return _execute(m, gate=gate, dry_run=dry_run)
'''


def generate(program: nodes.Program, source: str = "<string>", out: str = "compiled.py") -> str:
    skills = "\n".join(_emit_skill(s) for s in program.skills)
    return _HEADER.format(source=source, out=out, skills=skills)
